services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=api
    ports:
      - "58841:58841"
  event-store:
    container_name: event-store
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=event-store
    ports:
      - "62621:62621"
  gql:
    container_name: gql
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=gql
    ports:
      - "55955:55955"
  https:
    container_name: https
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=https
    ports:
      - "51997:51997"
